2021-06-17 21:36:01,008:INFO:Initializing load_model()
2021-06-17 21:36:01,009:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:36:25,039:INFO:Initializing load_model()
2021-06-17 21:36:25,039:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:36:25,071:INFO:Initializing predict_model()
2021-06-17 21:36:25,071:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x00000218DA14C550>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 21:36:25,072:INFO:Checking exceptions
2021-06-17 21:36:25,073:INFO:Preloading libraries
2021-06-17 21:36:25,074:ERROR:Pipeline not found. Exception:
2021-06-17 21:36:25,076:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2021-06-17 21:43:04,400:INFO:Initializing load_model()
2021-06-17 21:43:04,400:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:43:13,183:INFO:Initializing load_model()
2021-06-17 21:43:13,183:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:43:13,216:INFO:Initializing predict_model()
2021-06-17 21:43:13,217:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x0000020F6B130C40>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 21:43:13,217:INFO:Checking exceptions
2021-06-17 21:43:13,218:INFO:Preloading libraries
2021-06-17 21:43:13,218:ERROR:Pipeline not found. Exception:
2021-06-17 21:43:13,222:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2021-06-17 21:49:21,341:INFO:Initializing load_model()
2021-06-17 21:49:21,341:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:49:25,257:INFO:Initializing load_model()
2021-06-17 21:49:25,257:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 21:49:25,293:INFO:Initializing predict_model()
2021-06-17 21:49:25,296:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x0000020F6B37E8B0>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 21:49:25,301:INFO:Checking exceptions
2021-06-17 21:49:25,305:INFO:Preloading libraries
2021-06-17 21:49:25,309:ERROR:Pipeline not found. Exception:
2021-06-17 21:49:25,314:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2021-06-17 22:00:33,289:INFO:Initializing load_model()
2021-06-17 22:00:33,290:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 22:00:36,185:INFO:Initializing load_model()
2021-06-17 22:00:36,185:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 22:00:36,213:INFO:Initializing predict_model()
2021-06-17 22:00:36,216:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x0000020F6B394A00>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 22:00:36,218:INFO:Checking exceptions
2021-06-17 22:00:36,218:INFO:Preloading libraries
2021-06-17 22:00:36,219:ERROR:Pipeline not found. Exception:
2021-06-17 22:00:36,219:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2021-06-17 22:01:59,937:INFO:Initializing load_model()
2021-06-17 22:01:59,938:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 22:01:59,966:INFO:Initializing predict_model()
2021-06-17 22:01:59,967:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x0000020F6B121850>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 22:01:59,967:INFO:Checking exceptions
2021-06-17 22:01:59,967:INFO:Preloading libraries
2021-06-17 22:01:59,968:ERROR:Pipeline not found. Exception:
2021-06-17 22:01:59,968:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2021-06-17 22:02:03,356:INFO:Initializing load_model()
2021-06-17 22:02:03,357:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 22:02:05,454:INFO:Initializing load_model()
2021-06-17 22:02:05,454:INFO:load_model(model_name=model/modelo-final, platform=None, authentication=None, verbose=True)
2021-06-17 22:02:05,485:INFO:Initializing predict_model()
2021-06-17 22:02:05,485:INFO:predict_model(estimator=<catboost.core.CatBoostRegressor object at 0x0000020F6B3BBAF0>, probability_threshold=None, encoded_labels=True, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2021-06-17 22:02:05,487:INFO:Checking exceptions
2021-06-17 22:02:05,487:INFO:Preloading libraries
2021-06-17 22:02:05,489:ERROR:Pipeline not found. Exception:
2021-06-17 22:02:05,490:ERROR:Traceback (most recent call last):
  File "c:\users\dri_f\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8244, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

